# #####################################################################
# Automatically generated by qmake (2.01a) ter dez 8 11:59:00 2009
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += xml \
    sql
CONFIG += qxt \
    xml
QXT += core \
    web

# Input
HEADERS += webserver.h \
    webservice.h \
    simplesoapparser.h
SOURCES += main.cpp \
    webservice.cpp \
    webserver.cpp \
    simplesoapparser.cpp
