# #####################################################################
# Automatically generated by qmake (2.01a) ter dez 8 14:04:02 2009
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += gui \
    xml \
    core \
    network


# Input
HEADERS += client.h \
    qtsoap.h \
    mainwindow.h
SOURCES += client.cpp \
    main.cpp \
    qtsoap.cpp \
    mainwindow.cpp
FORMS += mainwindow.ui
